apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  selector:
    app: web-server
  ports:
    - protocol: TCP
      port: 80 # Exposed port on the service
      targetPort: 5000 # Port your app is running on in the container
  type: LoadBalancer # Expose the service externally
