name: Build Docker Container

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-web-server .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag my-web-server ${{ secrets.DOCKER_USERNAME }}/my-web-server:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-web-server:latest
